# typings/alsaaudio/__init__.pyi

# Konstanten (Einheiten)
VOLUME_UNITS_PERCENTAGE: int
VOLUME_UNITS_RAW: int
VOLUME_UNITS_DB: int

# Konstanten (Kanäle/Typen)
PCM_PLAYBACK: int
PCM_CAPTURE: int

def mixers(cardindex: int = ...) -> list[str]: ...
def card_indexes() -> list[int]: ...
def cards() -> list[str]: ...

class ALSAAudioError(Exception): ...

class Mixer:
    def __init__(
        self, control: str = ..., cardindex: int = ..., device: str = ...
    ) -> None: ...
    def cardname(self) -> str: ...
    def mixername(self) -> str: ...
    def getvolume(self, pcmtype: int = ..., units: int = ...) -> list[int]: ...
    def setvolume(
        self, volume: int, channel: int = ..., pcmtype: int = ..., units: int = ...
    ) -> None: ...
    def getrange(self, pcmtype: int = ..., units: int = ...) -> tuple[int, int]: ...
    def getmute(self) -> list[int]: ...
    def setmute(self, mute: int, channel: int = ...) -> None: ...
